# Generated by Django 5.0.6 on 2024-05-16 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeIngrediente', models.CharField(max_length=40)),
                ('valorEnergetico', models.DecimalField(decimal_places=2, max_digits=10)),
                ('carboidratos', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acuTotais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('acuAdicionais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gordTotais', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gordSaturadas', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gordTrans', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fibra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sodio', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeReceita', models.CharField(max_length=40)),
                ('medida', models.CharField(choices=[('g', 'gramas'), ('ml', 'mililitros')], max_length=11)),
                ('gluten', models.CharField(choices=[('zero gluten', 'Não Contém Glúten'), ('com gluten', 'Contém Glúten')], max_length=17)),
                ('lactose', models.CharField(choices=[('zero lactose', 'Zero Lactose'), ('baixa lactose', 'Baixo Teor de Lactose'), ('contem lactose', 'Contém Lactose')], max_length=22)),
                ('tipoDePorcao', models.CharField(choices=[('inteira', 'Porção Inteira'), ('quebrada', 'Porção Quebrada'), ('sem porcao', 'Sem Porção')], max_length=20)),
                ('porcaoEmb', models.IntegerField()),
                ('pesoFinal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('porcao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medidaCaseira', models.CharField(max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfil')),
            ],
        ),
        migrations.CreateModel(
            name='MeusIngredientes',
            fields=[
                ('ingrediente_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.ingrediente')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='usuarios.perfil')),
            ],
            bases=('app.ingrediente',),
        ),
    ]
