# Generated by Django 5.0.6 on 2024-05-18 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_meusingredientes_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingrediente',
            name='acuAdicionais',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='acuTotais',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='fibra',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='gordSaturadas',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='gordTotais',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='gordTrans',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='ingrediente',
            name='sodio',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
