# Generated by Django 5.0.6 on 2024-05-19 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_ingrediente_acuadicionais_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alergenico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeAlergenico', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='receita',
            name='ingrediente',
            field=models.ManyToManyField(related_name='receitas_com_ingrediente', to='app.ingrediente'),
        ),
        migrations.AddField(
            model_name='receita',
            name='meus_ingredientes',
            field=models.ManyToManyField(related_name='receitas_com_meus_ingredientes', to='app.meusingredientes'),
        ),
        migrations.AddField(
            model_name='receita',
            name='alegenicos',
            field=models.ManyToManyField(to='app.alergenico'),
        ),
    ]
