# Generated by Django 5.0.6 on 2024-07-11 21:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_receita_lactose_alter_receita_tipodeporcao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receita',
            name='alegenicos',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='ingrediente',
        ),
        migrations.RemoveField(
            model_name='receita',
            name='meus_ingredientes',
        ),
        migrations.AddField(
            model_name='alergenico',
            name='id_receita',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='app.receita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='receita',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='IngredientesReceita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_ingredientes', to='app.ingrediente')),
                ('id_meus_ingredientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receitas_meus_ingredientes', to='app.meusingredientes')),
                ('id_receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.receita')),
            ],
        ),
    ]
