# Generated by Django 5.0.7 on 2024-07-18 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_alergenico_id_receita_alergenicoreceita'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredientesreceita',
            name='id_meus_ingredientes',
        ),
        migrations.AddField(
            model_name='ingrediente',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MeusIngredientes',
        ),
    ]
