# Generated by Django 5.0.7 on 2024-08-07 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_ingredientesreceita_id_meus_ingredientes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientesreceita',
            name='qtdIngrediente',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
