# Generated by Django 5.0.7 on 2024-08-08 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_ingredientesreceita_qtdingrediente'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergenicoreceita',
            name='id_receita',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='app.receita'),
        ),
    ]
